### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by tcoyze**
I made a quick change to work for me. I was wondering what your thoughts were on this change from using sub_process.

### CODE REVIEW

**Comment by ovalhub** [comment]
> On Jan 18, 2017, at 13:18, Tyler Coyner <notifications@github.com> wrote:
> 
> I made a quick change to work for me. I was wondering what your thoughts were on this change from using sub_process.
> 
What if ICU_VERSION is not set in the env ?
What problem are you trying to solve ?

Andi..

**Comment by tcoyze** [comment]
My machine, MacOS, with icu4c 58.2 installed via brew had no `icu-config` available even with the environment variables set. Thus, it kept defaulting to using version 56. Instead of using the sub_process command I switched it out for a simple environment variable to be able to build the module.

**Comment by tcoyze** [comment]
There could very well be an issue on my end that is causing the module not to build properly with your current `setup.py`. However, I did see someone running into the same issue with an even more hacky fix, where they just hardcoded the icu4c version in the `setup.py`.

**Comment by ovalhub** [comment]
On Wed, 18 Jan 2017, Tyler Coyner wrote:

> My machine, MacOS, with icu4c 58.2 installed via brew had no `icu-config` 
> available even with the environment variables set. Thus, it kept 
> defaulting to using version 56. Instead of using the sub_process command I 
> switched it out for a simple environment variable to be able to build the 
> module.

I understand what you did. But what happens for people that do the normal 
install of ICU, have icu_config but no ICU_VERSION env var set ?
I think that you could change your patch to:
   - check ICU_VERSION
   - report that setup.py found it and display its value
   - if it is not set, use icu-config

Andi..

**Comment by tcoyze** [comment]
I resolved the issue. I just needed to finish building icu4c by `brew link icu4c`. Totally unrelated issue to your code base. However, I will make the changes that you suggested and see what you think. Thank you for being considerate of my modest changes.

**Comment by ovalhub** [comment]
Added check for ICU_VERSION env variable and error message in setup.py

**Pull request closed without merging**
