### PR TITLE
Rename docs.py as _icu_docs.py

### PR DESCRIPTION
**Pull request by jwilk**
`docs` is a very generic name for a module that is installed into global namespace.
Let's rename it as something clearly PyICU-specific and private.

### CODE REVIEW

**Comment by ovalhub** [comment]
On Tue, 19 Jul 2016, Jakub Wilk wrote:

> `docs` is a very generic name for a module that is installed into global namespace.
> Let's rename it as something clearly PyICU-specific and private.
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/ovalhub/pyicu/pull/23
>
> -- Commit Summary --
>
>  * Rename docs.py as _icu_docs.py
>
> -- File Changes --
>
>    R _icu_docs.py (0)
>    M icu.py (2)
>    M setup.py (2)
>
> -- Patch Links --
>
> https://github.com/ovalhub/pyicu/pull/23.patch
> https://github.com/ovalhub/pyicu/pull/23.diff

This doesn't seem to make a lot of sense.
docs.py is not imported into the global namespace, its contents are, and 
then not into the global namespace but into icu.py's.

The import statement in icu.py reads:  from docs import *
And docs is resolved according to the module lookup rules.
Now, I have no objections to renaming this file, no one should care what 
it's called to begin with but I'd like to understand the point of your patch 
first. I may be missing something.

Andi..

**Comment by jwilk** [comment]
Sorry for confusing wording!
By "global namespace" I meant namespace of top-level modules.
I've amended the commit message.
I hope it's clear now.

**Comment by wfdd** [comment]
Well, there's no particular need to be exposing `docs` globally, with or without the leading underscore.  This is a side-effect of not having placed the package source code inside a separate folder.  Ideally you'd wanna relocate the pair of `icu.py` and `docs.py` to an `icu` subfolder and rename the former to `__init__.py`.  Afterwards you'd have to make the following changed to the `setup` file:

```diff
-      py_modules=['icu', 'PyICU', 'docs'])
+      packages=['icu'])
+      py_modules=['PyICU'])
```

**Comment by ovalhub** [comment]
On Wed, 20 Jul 2016, [??ufd?] wrote:

> Well, there's no particular need to be exposing `docs` globally, with or 
> without the leading underscore.  This is a side-effect of not having 
> placed the package source code inside a separate folder.  Ideally you'd 
> wanna relocate the pair of `icu.py` and `docs.py` to an `icu` subfolder 
> and rename the former to `__init__.py`.  Afterwards you'd have to make the 
> following changed to the `setup` file:
>
> ```diff
> -      py_modules=['icu', 'PyICU', 'docs'])
> +      packages=['icu'])
> +      py_modules=['PyICU'])
> ```

Ok, so if that's what the actual issue is about, then please propose a patch 
that implements this solution.

Thanks !

Andi..

**Comment by kochelmonster** [comment]
Just for information: PyICU does not work with Faker (which installs a docs directory).
What is the status of this issue?

**Comment by ovalhub** [comment]
On Mon, 19 Dec 2016, kochelmonster wrote:

> Just for information: PyICU does not work with Faker (which installs a docs directory).
> What is the status of this issue?

Fixed now in HEAD.

**Comment by ovalhub** [comment]
fixed in HEAD now.

**Pull request closed without merging**
