### PR TITLE
Added missing conditionals around use of uscript features from newer ICU versions

### LINKED ISSUE #35: PyICU failing to build for icu vesion 4.2.1
Have installed libicu-dev and the version of it is 4.2.1.

```Downloading/unpacking PyICU==1.9.4
  Downloading PyICU-1.9.4.tar.gz (181kB): 181kB downloaded
  Running setup.py (path:/tmp/pip_build_root/PyICU/setup.py) egg_info for package PyICU
Installing collected packages: PyICU
  Running setup.py install for PyICU
    building '_icu' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c _icu.cpp -o build/temp.linux-x86_64-2.6/_icu.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c bases.cpp -o build/temp.linux-x86_64-2.6/bases.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c calendar.cpp -o build/temp.linux-x86_64-2.6/calendar.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c char.cpp -o build/temp.linux-x86_64-2.6/char.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    In file included from /usr/include/python2.6/Python.h:8:0,
                     from common.h:33,
                     from char.cpp:27:
    /usr/include/python2.6/pyconfig.h:1031:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
    /usr/include/features.h:164:0: note: this is the location of the previous definition
    /usr/include/python2.6/pyconfig.h:1040:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
    /usr/include/features.h:166:0: note: this is the location of the previous definition
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c charset.cpp -o build/temp.linux-x86_64-2.6/charset.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c collator.cpp -o build/temp.linux-x86_64-2.6/collator.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c common.cpp -o build/temp.linux-x86_64-2.6/common.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    common.cpp: In function 'void _init_common(PyObject*)':
    common.cpp:1448:5: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
    common.cpp:1448:5: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
    /usr/include/unicode/tmutfmt.h: At global scope:
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c dateformat.cpp -o build/temp.linux-x86_64-2.6/dateformat.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c errors.cpp -o build/temp.linux-x86_64-2.6/errors.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c format.cpp -o build/temp.linux-x86_64-2.6/format.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c idna.cpp -o build/temp.linux-x86_64-2.6/idna.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    In file included from /usr/include/python2.6/Python.h:8:0,
                     from common.h:33,
                     from idna.cpp:27:
    /usr/include/python2.6/pyconfig.h:1031:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
    /usr/include/features.h:164:0: note: this is the location of the previous definition
    /usr/include/python2.6/pyconfig.h:1040:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
    /usr/include/features.h:166:0: note: this is the location of the previous definition
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c iterators.cpp -o build/temp.linux-x86_64-2.6/iterators.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c layoutengine.cpp -o build/temp.linux-x86_64-2.6/layoutengine.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c locale.cpp -o build/temp.linux-x86_64-2.6/locale.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    In file included from /usr/include/python2.6/Python.h:8:0,
                     from common.h:33,
                     from locale.cpp:35:
    /usr/include/python2.6/pyconfig.h:1031:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]
    /usr/include/features.h:164:0: note: this is the location of the previous definition
    /usr/include/python2.6/pyconfig.h:1040:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]
    /usr/include/features.h:166:0: note: this is the location of the previous definition
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c normalizer.cpp -o build/temp.linux-x86_64-2.6/normalizer.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c numberformat.cpp -o build/temp.linux-x86_64-2.6/numberformat.o -DPYICU_VER="1.9.4"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]
    numberformat.cpp: In function 'PyObject* t_numberformat_isLenient(t_numberformat*)':
    numberformat.cpp:912:29: error: 'class icu_4_2::NumberFormat' has no member named 'isLenient'
    numberformat.cpp: In function 'PyObject* t_numberformat_setLenient(t_numberformat*, PyObject*)':
    numberformat.cpp:923:23: error: 'class icu_4_2::NumberFormat' has no member named 'setLenient'
    /usr/include/unicode/tmutfmt.h: At global scope:
    /usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/PyICU/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FzWkfv-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.6

copying icu.py -> build/lib.linux-x86_64-2.6

copying PyICU.py -> build/lib.linux-x86_64-2.6

copying docs.py -> build/lib.linux-x86_64-2.6

running build_ext

building '_icu' extension

creating build/temp.linux-x86_64-2.6

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c _icu.cpp -o build/temp.linux-x86_64-2.6/_icu.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c bases.cpp -o build/temp.linux-x86_64-2.6/bases.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c calendar.cpp -o build/temp.linux-x86_64-2.6/calendar.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c char.cpp -o build/temp.linux-x86_64-2.6/char.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

In file included from /usr/include/python2.6/Python.h:8:0,

                 from common.h:33,

                 from char.cpp:27:

/usr/include/python2.6/pyconfig.h:1031:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]

/usr/include/features.h:164:0: note: this is the location of the previous definition

/usr/include/python2.6/pyconfig.h:1040:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]

/usr/include/features.h:166:0: note: this is the location of the previous definition

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c charset.cpp -o build/temp.linux-x86_64-2.6/charset.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c collator.cpp -o build/temp.linux-x86_64-2.6/collator.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c common.cpp -o build/temp.linux-x86_64-2.6/common.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

common.cpp: In function 'void _init_common(PyObject*)':

common.cpp:1448:5: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

common.cpp:1448:5: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

/usr/include/unicode/tmutfmt.h: At global scope:

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c dateformat.cpp -o build/temp.linux-x86_64-2.6/dateformat.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c errors.cpp -o build/temp.linux-x86_64-2.6/errors.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c format.cpp -o build/temp.linux-x86_64-2.6/format.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c idna.cpp -o build/temp.linux-x86_64-2.6/idna.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

In file included from /usr/include/python2.6/Python.h:8:0,

                 from common.h:33,

                 from idna.cpp:27:

/usr/include/python2.6/pyconfig.h:1031:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]

/usr/include/features.h:164:0: note: this is the location of the previous definition

/usr/include/python2.6/pyconfig.h:1040:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]

/usr/include/features.h:166:0: note: this is the location of the previous definition

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c iterators.cpp -o build/temp.linux-x86_64-2.6/iterators.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c layoutengine.cpp -o build/temp.linux-x86_64-2.6/layoutengine.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c locale.cpp -o build/temp.linux-x86_64-2.6/locale.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

In file included from /usr/include/python2.6/Python.h:8:0,

                 from common.h:33,

                 from locale.cpp:35:

/usr/include/python2.6/pyconfig.h:1031:0: warning: "_POSIX_C_SOURCE" redefined [enabled by default]

/usr/include/features.h:164:0: note: this is the location of the previous definition

/usr/include/python2.6/pyconfig.h:1040:0: warning: "_XOPEN_SOURCE" redefined [enabled by default]

/usr/include/features.h:166:0: note: this is the location of the previous definition

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c normalizer.cpp -o build/temp.linux-x86_64-2.6/normalizer.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c numberformat.cpp -o build/temp.linux-x86_64-2.6/numberformat.o -DPYICU_VER="1.9.4"

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for Ada/C/ObjC but not for C++ [enabled by default]

numberformat.cpp: In function 'PyObject* t_numberformat_isLenient(t_numberformat*)':

numberformat.cpp:912:29: error: 'class icu_4_2::NumberFormat' has no member named 'isLenient'

numberformat.cpp: In function 'PyObject* t_numberformat_setLenient(t_numberformat*, PyObject*)':

numberformat.cpp:923:23: error: 'class icu_4_2::NumberFormat' has no member named 'setLenient'

/usr/include/unicode/tmutfmt.h: At global scope:

/usr/include/unicode/tmutfmt.h:231:29: warning: 'UBool icu_4_2::hashTableValueComparator(UHashTok, UHashTok)' declared 'static' but never defined [-Wunused-function]

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/PyICU/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FzWkfv-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/PyICU
Storing debug log for failure in /root/.pip/pip.log
```

Similar output is generated by cloning master and attempting `python setup.py install`. My first guess is that libicu4_2 numberformat doesn't have the isLenient and setLenient methods (seen http://icu.sourcearchive.com/documentation/4.2/classNumberFormat.html)

### PR DESCRIPTION
**Pull request by kdparker**
Fixes #35 (I can run the full install with these changes active). Moved the uscript features up as the oldest version I could find them in was 51. Moved the codes down to 4.6 as the code within libicu states they were added in 4.6

### CODE REVIEW

**Comment by ovalhub** [comment]
Thank you for the patch but it's not completely correct.
The functions you put under version 51 are available since 49.

http://icu-project.org/apiref/icu4c/uscript_8h.html#aec5e62350193d649747846d4298ef9d7

No worries, I'll fix it.

Andi..

**Comment by kdparker** [comment]
Sounds good, thanks again for the help

**Comment by ovalhub** [comment]
On Wed, 9 Nov 2016, Keegan Parker wrote:

> Sounds good, thanks again for the help

And MANDAEAN is available since 3.6:
http://icu-project.org/apiref/icu4c/uscript_8h.html#a5036ff9ca2a7f1d2bde07875bb235df0a648e6bc51d2c978ac75077e08d1f9a71

Andi..

**Comment by ovalhub** [comment]
On Wed, 9 Nov 2016, Keegan Parker wrote:

> Sounds good, thanks again for the help

Thank you !
In repeated your patch (with correct versions) and checked it into trunk.

Andi..

**Pull request closed without merging**
