### PR TITLE
Adding arm64 Travis Support

### PR DESCRIPTION
**Pull request by ossdev07**
Travis-CI has added support for ARM64. Added ARM64 job in Travis-CI.

### CODE REVIEW

**Comment by ovalhub** [comment]
Thank you for your contribution. Travis is asking its freebie open source users to be "reasonable" with the number of job variants setup. Could you please remove the arm64 variants with older ICU or python versions that are unlikely to exist in the wild or that existed before arm64 was a thing ? (thanks again)

**Comment by rhenwood-arm** [comment]
@ossdev07 : I suggest you limit to python 3.7 and 3.8, and three of the most recent ICU_VERSIONs?

**Comment by ossdev07** [comment]
Ping @ovalhub we have incorporated the changes according to your suggestion kindly have a look on this commit.

**Comment by ovalhub** [comment]
Thank you for the contribution.

**Pull request merged**
