### PR TITLE
ENH:Create universal wheel on PyPi for `pyicu`

### PR DESCRIPTION
**Pull request by linwoodc3**
If this is too instructive, forgive me.  Just wanted to require minimal effort from original author since this is me asking you to add something to your repository.  

# Summary of Merge Request
@ovalhub, this merge request creates a “Universal Wheel” to [resolve an issue on the MacOS where pyicu's inability to fully install via `pip install pyicu`](https://github.com/aboSamoor/polyglot/issues/80) causes an error with [`polyglot`](https://github.com/aboSamoor/polyglot), which is a multilingual NLP library created by @aboSamoor .

## Details of Request

Request @ovalhub accept merge request, and run the following commands to update the [PyICU PyPi packaging](https://pypi.python.org/pypi/PyICU/1.9.5).  This will include a universal wheel in the `File` section.  

The problem encountered and fix are [discussed in detail here](https://github.com/aboSamoor/polyglot/issues/80#issuecomment-266301717).

## What's the Change?
Just created a simple `setup.cfg` file as described in the [Universal Wheels section](https://packaging.python.org/distributing/#universal-wheels) of the **[Python Packaging User Guide](https://packaging.python.org/)**.  The exact content of the simple setup.cfg [file is here](https://github.com/pypa/sampleproject/blob/master/setup.cfg).

## How to "update" your Packaging
After this file is in the  master `pyicu` repository, you run the following commands, as described in the [Packaging User Guide](https://packaging.python.org/distributing/#packaging-your-project):
```bash
>>> cd pyicu
>>> python setup.py bdist_wheel --universal  # create the universal wheel 
>>> python setup.py bdist_wheel # creates platform specific wheel just in case
```

Now, the last step is just uploading the distribution to PyPi. If you use twine (recommended approach, see [here for security discussion](https://packaging.python.org/distributing/#upload-your-distributions)):
```bash
>>> twine upload dist/*
```

Or the `setuptools` alternative (not recommended, see [here for security discussion](https://packaging.python.org/distributing/#upload-your-distributions)):
```bash
>>> python setup.py sdist bdist_wheel upload
```

This should [solve one of the problems discussed in the `polyglot` issue](https://github.com/aboSamoor/polyglot/issues/80#issuecomment-266301717).

### CODE REVIEW

**Comment by ovalhub** [comment]
> On Dec 11, 2016, at 13:46, Linwood Creekmore <notifications@github.com> wrote:
> 
> If this is too instructive, forgive me. Just wanted to require minimal effort from original author since this is me asking you to add something to your repository.
> 
> Summary of Merge Request
> 
> @ovalhub, this merge request creates a “Universal Wheel” to resolve an issue on the MacOS where pyicu's inability to fully install via pip install pyicu causes an error with polyglot, which is a multilingual NLP library created by @aboSamoor .
> 
> Details of Request
> 
> Request @ovalhub accept merge request, and run the following commands to update the PyICU PyPi packaging. This will include a universal wheel in the File section.
> 

I've never heard of such "wheels" before but reading the link above I see this:

Only use the --universal setting, if:

Your project runs on Python 2 and 3 with no changes (i.e. it does not require 2to3).
Your project does not have any C extensions.
PyICU has no python code in it (except tests), it's a pure C++ module that links with ICU and Python. In other words, it's C extension. This would seem to contradict item 2. quoted above, no ?
And 2to3 is needed to run tests on Python 3, contradicting 1. if that applies to tests.

Please explain, instruct me, why all this makes sense and what it achieves. On my end, I'll try pip install to see if I can reproduce the failure you reported.

Thanks !

Andi..

**Comment by linwoodc3** [comment]
No problem. Thanks for considering this.   I'll explain as best as I can (not a Comp Sci person).  I figured this out by trouble shooting and just reading tons.

###  What does a "wheel" accomplish?
It resolved the install issues I had for a project that uses pyicu as a dependency; will likely resolve other issues, but also, aligns your `pyicu` project to the new [PEP Distribution Standard](https://www.python.org/dev/peps/pep-0427/) (not so new since standard was approved in Feb 2013) , which uses the wheel binary package format  because it frees installers from having to know about the build system, saves time by amortizing compile time over many installations, and removes the need to install a build system in the target environment.

I created two workarounds for `pyicu` to successfully install on [Python 2.7](https://gist.github.com/linwoodc3/fc7d986401671159484266c937d53b9c) and [Python 3.5](https://gist.github.com/linwoodc3/8704bbf6d1c6130dda02bbc28967a9e6), but I think this small merge would help the problem (you would add a universal wheel to your PyPi distribution).

### You may ask, but who cares about Python wheels?  Why does `pyicu` need it?

The webpage [pythonwheels](http://pythonwheels.com/) describes this benefit best, but also directly relates to pyicu as it's a C extension as you said above.  This is text pasted from the webpage, but note the bullet I bolded below):
 -------------------
## What are wheels?
Wheels are the new standard of python distribution and are intended to replace eggs. Support is offered in pip >= 1.4 and setuptools >= 0.8.

## Advantages of wheels
*  Faster installation for pure python and native C extension packages.
*  Avoids arbitrary code execution for installation. (Avoids setup.py)
*  **Installation of a C extension does not require a compiler on Windows or OS X.**
*  Allows better caching for testing and continuous integration.
*  Creates .pyc files as part of installation to ensure they match the python interpreter used.
*  More consistent installs across platforms and machines.

I believe adding this file will fix the install problem for the scientific community folks who use anaconda. Moreover, it will help the folks who want to use `polyglot`, which depends on `pyicu`.

I created two work to install pyicu on a MacOS machine running Anaconda and using [Python 2.7](https://gist.github.com/linwoodc3/fc7d986401671159484266c937d53b9c) or [Python 3.5](https://gist.github.com/linwoodc3/8704bbf6d1c6130dda02bbc28967a9e6)

### Recreating my problem
To recreate the problem I experienced (I'm on a Mac), I think you may need to have Anaconda installed.  It's a [scientific computing distribution](https://anaconda.org/about).

Here are the steps for me:

```bash
pip install polyglot
python
```

```python
from polyglot.text import Text, Word
```  

That always gives me an error like this:
`Library not loaded: libicui18n.54.dylib` which comes from something called `docs`, line 23: 

Here is a screen capture of the traceback:
screen shot 2016-12-11 at 6 26 04 pm


Hope this explains it!

**Comment by ovalhub** [comment]
> On Dec 11, 2016, at 15:40, Linwood Creekmore <notifications@github.com> wrote:
> 
> No problem. Thanks for considering this. I'll explain as best as I can (not a Comp Sci person). I figured this out by trouble shooting and just reading tons.
> 
> What does a "wheel" accomplish?
> 
> It resolved the install issues I had for a project that uses pyicu as a dependency; will likely resolve other issues, but also, aligns your pyicu project to the new PEP Distribution Standard (not so new since standard was approved in Feb 2013) , which uses the wheel binary package format because it frees installers from having to know about the build system, saves time by amortizing compile time over many installations, and removes the need to install a build system in the target environment.
> 
Aah, so it's a way to distribute binaries. Well, this can't work with PyICU since it can't be a universal binary. Each binary PyICU is different depending on:
   - version of ICU compiled and linked against (a dozen or so)
   - version of OS (let's say three: linux, macos, windows)
   - version of Python (let's say 3: 2.7.x, 3.x, 3.y, 
   - version of PyPI (if used)
where 3.x is before the new string implementation and 3.y after)
That's at minimum 12*3*3*2 = 216 different binary versions. Including them all in a wheel would make for huge downloads for everyone and lots's of users would still not be covered by any of these 216 versions. PyICU is not pure Python, it's pure C++, there is no python code in it.

More comments below.
> I created two workarounds for pyicu to successfully install on Python 2.7 and Python 3.5, but I think this small merge would help the problem (you would add a universal wheel to your PyPi distribution).
> 
> You may ask, but who cares about Python wheels? Why does pyicu need it?
> 
> The webpage pythonwheels describes this benefit best, but also directly relates to pyicu as it's a C extension as you said above. This is text pasted from the webpage, but note the bullet I bolded below):
> 
> What are wheels?
> 
> Wheels are the new standard of python distribution and are intended to replace eggs. Support is offered in pip >= 1.4 and setuptools >= 0.8.
> 
> Advantages of wheels
> 
> Faster installation for pure python and native C extension packages.
> Avoids arbitrary code execution for installation. (Avoids setup.py)
> Installation of a C extension does not require a compiler on Windows or OS X.
Sadly, it does require a compiler for PyICU because the binary version of PyICU depends on the version of the ICU library it is compiled against and linked with. Each version of ICU has different APIs, old ones disappear, new ones appear with each release. One does need a working compiler and linker for building PyICU (and ICU before that).
> Allows better caching for testing and continuous integration.
> Creates .pyc files as part of installation to ensure they match the python interpreter used.
There are no .pyc files in PyICU, it has no python code (except for tests).
> More consistent installs across platforms and machines.
> I believe adding this file will fix the install problem for the scientific community folks who use anaconda. Moreover, it will help the folks who want to use polyglot, which depends on pyicu.
> 
Yes, but then you need to create a specific distribution of PyICU for Anaconda / Polyglot users where the version of ICU is frozen (to 54.1, right ?), not the latest version of ICU others users expect it to wrap (like 58.1, currently). That would be a binary fork of PyICU specific to this use case. You're welcome to create one.
> I created two work to install pyicu on a MacOS machine running Anaconda and using Python 2.7 or Python 3.5
> 
For what version of ICU ?
> Recreating my problem
> 
> To recreate the problem I experienced (I'm on a Mac), I think you may need to have Anaconda installed. It's a scientific computing distribution.
> 
> Here are the steps for me:
> 
> pip install polyglot
> python
> from polyglot.text import Text, Word
> That always gives me an error like this:
> Library not loaded: libicui18n.54.dylib which comes from something called docs, line 23:
> 
Do you have ICU 54 installed on your machine before you launch that command ?

Andi..

**Comment by linwoodc3** [comment]
@ovalhub , yes, I did tests with 58.1 and 54.1.0, and 54.1.1.  Only 54.1.1 works.  Weird, but that's what i found through trial and error.  

this gets me icu 54.1.1:
```bash
conda install -c ccordoba12 icu=54.1
``` 

which is from here: https://anaconda.org/ccordoba12/icu 

None of these work (which is why it was confusing..lots of trial and error):
```bash
conda install icu # installs 54.1.0, doesn't work
conda install -c conda-forge icu=58.1 # doesn't work
conda install -c anaconda icu=57.1  # doesn't work
```

Even tried Homebrew, but Homebrew only install 58.1:
http://brewformulas.org/Icu4c 
```bash
brew install icu4c
```

All gave me that `Library not loaded: libicui18n.54.dylib` except for the icu 54.1.1 install. 

But, even with that, when I tried to run `polyglot`, which uses `pyicu`, I got that same error.  Only using `easy_install` worked.  But then, I cloned and made the universal wheel, and pip install of the whl file worked perfectly.

**Comment by linwoodc3** [comment]
I think the main problem is `pip install`; something about the `easy_install` works, while it doesn't work in the `pip`.  To be clear, I don't get an error on the `pip install pyicu`, but when I try to import something from pyicu, it gives an error.  However, when I install `pyicu` with `easy_install`, I don't get that error.  

## Another Option (more simple)
When I use pip to download your tar file, you have the `setup.cfg`.  I believe adding a simple line as you see in this pic would do the trick:

screen shot 2016-12-11 at 7 29 14 pm

Then, you would run these commands, and redistribute to PyPi.

```bash
>>> cd pyicu
>>> python setup.py bdist_wheel --universal  # create the universal wheel 
>>> python setup.py bdist_wheel # creates platform specific wheel just in case
>>> twine upload dist/*
#or
>>> python setup.py sdist bdist_wheel upload

Let me know if I can assist anymore. Thanks again for considering.

**Comment by ovalhub** [comment]
> On Dec 11, 2016, at 16:32, Linwood Creekmore <notifications@github.com> wrote:
> 
> I think the main problem is pip install; something about the easy_install works, while it doesn't work in the pip. To be clear, I don't get an error on the pip install pyicu, but when I try to import something from pyicu, it gives an error. However, when I install pyicu with easy_install, I don't get that error.
> 
> Another Option (more simple)
> 
> When I use pip to download your tar file, you have the setup.cfg. I believe adding a simple line as you see in this pic would do the trick:
> 
> 
> 

Did you understand my points about why PyICU can't be universal = 1 ?
> Then, you would run these commands, and redistribute to PyPi.
> 
I cannot distribute a PyICU binary on PyPI as it wouldn't work for any people that aren't running the same combination compiler, OS, ICU, Python that I used to build it. Did my earlier points about that make sense ?

Andi..

**Comment by linwoodc3** [comment]
I'm Sorry @ovalhub , I missed the earlier comments.  Went back, read, and understand your point. The combinatorics make this undoable as the size would blow up and things change too much.  This [comment from the numba maintainers made it hit home](https://groups.google.com/a/continuum.io/d/msg/numba-users/oe5yqCAluuw/DxYHyZ00hWAJ).  

Yes, I think polyglot is locked to 54.1.1 (not other way to explain all the errors); I'll look into how I create the binary fork you mentioned (have to figure out how to do it).  

Thanks for considering; Learned a bit from you too!!! 

I have the workarounds in Gists so hopefully people will come up on those when they run into errors. 

I'll link in case a Google search gets them to this page:

*  [Workaround for `pyicu` error in Anaconda/Python 2.7 config](https://gist.github.com/linwoodc3/fc7d986401671159484266c937d53b9c) 
*  [Workaround for `pyicu` error in Anaconda/Python 3.5 config](https://gist.github.com/linwoodc3/8704bbf6d1c6130dda02bbc28967a9e6)

Feel free to close; or do I close??

**Comment by ovalhub** [comment]
> On Dec 11, 2016, at 18:32, Linwood Creekmore <notifications@github.com> wrote:
> 
> I'm Sorry @ovalhub , I missed the earlier comments.  Went back, read, and understand your point. The combinatorics make this undoable as the size would blow up and things change too much. This comment from the numba maintainers made it hit home.
> 
> Yes, I think polyglot is locked to 54.1.1 (not other way to explain all the errors); I'll look into how I create the binary fork you mentioned (have to figure out how to do it).
> 
> Thanks for considering; Learned a bit from you too!!!
> 
> I have the workarounds in Gists so hopefully people will come up on those when they run into errors.
> 
> I'll link in case a Google search gets them to this page:
> 
> Workaround for pyicu error in Anaconda/Python 2.7 config
> Workaround for pyicu error in Anaconda/Python 3.5 config
> Feel free to close; or do I close??
> 
You're welcome to close the issue if you like.

Andi..

**Comment by asottile** [comment]
fwiw, a "universal" wheel is inappropriate for packages which have binary dependencies (such as this one) as universal is intended for pure python packages

**Comment by apnewberry** [comment]
> I cannot distribute a PyICU binary on PyPI as it wouldn't work for any people that aren't running the same combination compiler, OS, ICU, Python that I used to build it.

I believe it is possible to provide prebuilt binaries for the people who can use them and still provide source distributions for people who can't. That would be one wheel for each target platform and version. There is even a [third-party PyPI package](https://pypi.org/project/PyICU-binary/#files) that seems to be doing this for linux versions. For example the `coverage.py` project offers [many different wheels](https://pypi.org/project/coverage/#files), and `pip install coverage` will automatically select the right one for the user's platform. It is also common for open-source projects to take advantage of free continuous-integration server time to build artifacts on multiple platforms, such as on Travis, Appveyor, and CircleCI. 

As far as I know, the main thing required for getting started is just uploading the built distribution like so:
```
python setup.py sdist bdist_wheel 
twine upload dist/*
```

This would allow users on compatible platforms to `pip install pyicu` without having to build it themselves.

**Comment by ovalhub** [comment]
On Sun, 27 Jan 2019, apnewberry wrote:

>> I cannot distribute a PyICU binary on PyPI as it wouldn't work for any 
>> people that aren't running the same combination compiler, OS, ICU, Python 
>> that I used to build it.
>
> I believe it is possible to provide prebuilt binaries for the people who 
> can use them and still provide source distributions for people who can't. 
> That would be one wheel for each target platform and version. There is 
> even a [third-party PyPI 
> package](https://pypi.org/project/PyICU-binary/#files) that seems to be 
> doing this for linux versions. For example the `coverage.py` project 
> offers [many different wheels](https://pypi.org/project/coverage/#files), 
> and `pip install coverage` will automatically select the right one for the 
> user's platform. It is also common for open-source projects to take 
> advantage of free continuous-integration server time to build artifacts on 
> multiple platforms, such as on Travis, Appveyor, and CircleCI.
>
> As far as I know, the main thing required for getting started is just 
> uploading the built distribution like so: ``` python setup.py sdist 
> bdist_wheel twine upload dist/* ```
>
> This would allow users on compatible platforms to `pip install pyicu` 
> without having to build it themselves.

Are you proposing to set this up and maintain it ?
If so, I suggest you fork pyicu into a new pyicu-binaries project and if the 
process you implement proves to work as expected and if the failure modes 
are better than the current build-from-source situation, we could consider 
merging the fork back with pyicu proper - assuming you stick around for 
the long term and keep the build configurations current with new binary
combinations as they appear.

**Comment by apnewberry** [comment]
May I ask what commands you currently run to produce and release a new version?

**Comment by ovalhub** [comment]
> On Jan 27, 2019, at 20:13, apnewberry <notifications@github.com> wrote:
> 
> May I ask what commands you currently run to produce and release a new version?
> 
$ python setup.py register sdist

**Comment by apnewberry** [comment]
> Are you proposing to set this up and maintain it ?

I'm not prepared to take on that responsibility. I did want to share what I understand about what would be involved.

I believe the [current recommendation](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives) from PyPA boils down to 

```
python setup.py sdist bdist_wheel 
twine upload dist/*
```

and assuming the setup.py is written per the docs, I think that'll upload the source distribution and the wheel appropriate to the platform executing the command. It's also possible to produce wheels for multiple linux targets using the [manylinux project](https://github.com/pypa/manylinux).

**Comment by asottile** [comment]
A note on manylinux, for libraries which typically would link against a system library (for example, `pyicu` typically links against `libicudata.so.XX`, `libicui18n.so.XX`, `libicuuc.so.XX`) -- a manylinux wheel would involve *vendoring* those shared libraries into the wheel (`auditwheel` provides this functionality for you).

This ~might be undesirable as it removes the benefits of dynamic linking from a security perspective -- that is you no longer get benefit from your system package manager shipping security patches to libraries that are dynamically linked.  By extension, this ~probably makes releasing pyicu necessary if a security issue happened in the `libicu*.so.XX` libraries which it vendors.

That said, once you have a script which can build manylinux wheels, the rest is pretty easy (usually via docker) -- here's some examples from my projects (not super sophisticated): [sass/libsass-python](https://github.com/sass/libsass-python/blob/master/build_manylinux_wheels.py) [asottile/setuptools-golang](https://github.com/asottile/setuptools-golang/blob/fe4aa2d49d32847f89ea59b0c4578d6e7c1ce97b/setuptools_golang.py#L162-L195) (_NOTE_: I've only manylinux packaged things *without* `.so` dependencies due to the reason I mentioned above)

**Comment by abitrolly** [comment]
Just a note that `pip` already generates the wheel while installing PyICU for target Linux.

image

https://github.com/chubin/cheat.sh/runs/1409411905#step:3:75

**Comment by asottile** [comment]
@abitrolly that's a wheel specific to your machine built for the pip cache and isn't manylinux compatible / distributable (it links against whatever version of libicu you have installed on your machine)

**Pull request closed without merging**
