### PR TITLE
Expand Travis-CI scope

### PR DESCRIPTION
**Pull request by SethMMorton**
This is intended to address and close issue #117.

This PR will take many iterations to get correct, so I have prefixed the title with WIP to indicate it is a work-in-progress. I will remove WIP when I think it is read to merge.

- [x] Testing against multiple `icu4c` versions
- [x] Testing against multiple Python versions
- [x] Testing on Linux
- [x] Testing on macos
- [ ] Testing on Windows
- ~~On Linux, testing against both clang and GCC (not sure if this is needed?)~~

### CODE REVIEW

**Comment by ovalhub** [comment]
On Thu, 14 Nov 2019, Seth Morton wrote:

> This is intended to address and close issue #117.
>
> This PR will take many iterations to get correct, so I have prefixed the title with WIP to indicate it is a work-in-progress. I will remove WIP when I think it is read to merge.
>
> - [ ] Testing against multiple `icu4c` versions
> - [ ] Testing against multiple Python versions
> - [ ] Testing on Linux
> - [ ] Testing on macos
> - [ ] Testing on Windows
> - [ ] On Linux, testing against both clang and GCC (not sure if this is needed?)

One thing to keep in mind with C++ compilers requirements is that
ICU >= 60 (?) requires C++ 11.

**Comment by SethMMorton** [comment]
On macos I get the following message from the `setup.py`

```
    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-v5paf2q7/setup.py", line 183, in <module>
        raise RuntimeError('''
    RuntimeError:
    Please install pkg-config on your system or set the PYICU_CFLAGS environment
    variable to the flags required by the C++ compiler to find the header files
    for ICU, and possibly -std=c++11 if using ICU version >= 60
    
    
    Building PyICU 2.4.2 for ICU 65.1
    
    (running 'icu-config --cxxflags --cppflags')
    Could not configure CFLAGS with icu-config
```

How do you build on macos?

**Comment by SethMMorton** [comment]
Link to above issue: https://travis-ci.com/SethMMorton/pyicu/builds/136610331

**Comment by ovalhub** [comment]
On Thu, 14 Nov 2019, Seth Morton wrote:

> On macos I get the following message from the `setup.py`
>
> ```
>    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'
>
>    During handling of the above exception, another exception occurred:
>
>    Traceback (most recent call last):
>      File "<string>", line 1, in <module>
>      File "/private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-v5paf2q7/setup.py", line 183, in <module>
>        raise RuntimeError('''
>    RuntimeError:
>    Please install pkg-config on your system or set the PYICU_CFLAGS environment
>    variable to the flags required by the C++ compiler to find the header files
>    for ICU, and possibly -std=c++11 if using ICU version >= 60
>
>
>    Building PyICU 2.4.2 for ICU 65.1
>
>    (running 'icu-config --cxxflags --cppflags')
>    Could not configure CFLAGS with icu-config
> ```
>
> How do you build on macos?

I build ICU from a source download and it comes with icu-config.
   cd sources
   ./runConfigureICU MacOSX
   make
   make install

If one doesn't have either icu-config or pkg-config on macos (or elsewhere) 
installed, they are supposed to edit setup.py or set env vars so that the 
build gets configured for their environment:
   edit INCLUDES or get it from PYICU_INCLUDES env var
   same for CFLAGS or PYICU_CFLAGS
            LFLAGS or PYICU_LFLAGS
            LIBRARIES or PYICU_LIBRARIES

**Comment by SethMMorton** [comment]
OK.  Looks like the `.travis-ci.yml` previously set up did not use `runConfigureICU`, but something else.  I'll update the build step to "do the right thing", and hopefully that fixes it.

**Comment by SethMMorton** [comment]
It looks like the jobs have stopped running in Travis... did you disconnect?

**Comment by ovalhub** [comment]
On Thu, 14 Nov 2019, Seth Morton wrote:

> It looks like the jobs have stopped running in Travis... did you disconnect?

I haven't touched anything since setting it up yesterday.
Tomorrow, I intend to switch to .org if that proves necessary.

**Comment by SethMMorton** [comment]
Oh, sorry.  I pushed a bad config. It's working now.

**Comment by SethMMorton** [comment]
Two questions about `icu-config`

1. There is no file called that in the ICU repo, so I assume it is created *after* one of the `configure` or `make` step - where is it placed? I'm guessing I need to modify my `$PATH` to that location to properly build.
2. In the PyICU `setup.py` it seems to assume that `icu-config` is on the `$PATH` - is this the case in general if `icu4c` is installed?

**Comment by ovalhub** [comment]
On Thu, 14 Nov 2019, Seth Morton wrote:

> Two questions about `icu-config`
>
> 1. There is no file called that in the ICU repo, so I assume it is created *after* one of the `configure` or `make` step - where is it placed? I'm guessing I need to modify my `$PATH` to that location to properly build.
> 2. In the PyICU `setup.py` it seems to assume that `icu-config` is on the `$PATH` - is this the case in general if `icu4c` is installed?

For me, it's installed in /usr/local/bin, so it's on PATH normally.
The PyICU user is responsible for a providing a functional ICU installation.
That includes having icu-config (which is deprecated, by the way) or 
pkg-config (the new way, more standard) or setting env vars (or editing 
setup.py)

In your travis setup, if you're building ICU from scratch, you can configure 
it so that you know where it's putting its headers and libraries and thus 
provide env vars instead if you prefer not to depend on icu-|pkg-config.

**Comment by ovalhub** [comment]
Sorry for the noise, it seems that since 05/2018 all travis-ci setups should be using the .com flavor.
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by SethMMorton** [comment]
> Sorry for the noise, it seems that since 05/2018 all travis-ci setups should be using the .com flavor.

Got it. Thanks.

**Comment by SethMMorton** [comment]
@ovalhub OK, I have everything set up except Windows (which I plan to attempt). Here is the link to the build with this setup:

https://travis-ci.com/SethMMorton/pyicu/builds/136782659

- The currently active Python versions (2.7, 3.5, 3.6, 3.7, and 3.8) are testing against ICU 65.1 and 55.2 (a random non-latest version I chose)
- All other ICU versions going back to 50.2 are tested against Python 3.8.
- MacOS is tested against ICU 65.1 and Python 3.8 (could do more, but not sure there is much value)

This is a LOT of builds. I have set up caching so hopefully ICU does not need to be constantly re-built, just PyICU, but still - Travis-CI has this to say about running a lot of jobs:

> If you are on an open-source plan, please remember that Travis CI provides this service free of charge to the community. So please only specify the matrix you actually need.

With that in mind, do you REALLY need to test against all previous ICU versions? Here is my analysis of the failure modes from the linked build:

- `NameError: name 'LocaleMatcher' is not defined`
  - ICU versions 64.2, 63.2, 62.2, 61.2, 60.3, 58.3
- Compilation errors arising from `Edits` class
  - ICU version 59.2
- Undefined symbol at runtime (something related to `FontInstance`)
  - ICU versions 57.2, 56.2, 55.2, 54.2, 51.3
- Missing members from `RelativeDateTimeFormatter`
  - ICU version 53.2 
- `gcc: error: unrecognized command line option '-Qunused-arguments'`
  - ICU version 52.2
- `error: invalid new-expression of abstract class type 'PythonReplaceable'` (plus SO MANY compiler warnings)
  - ICU version 50.2

I think it would be wise to pick a representative selection of active versions, perhaps 65.1, 64.2, 59.2, 57.2, 53.2, 52.2, and 50.2 (although care should be taken to make sure all of  57.2, 56.2, 55.2, 54.2, and 51.3 pass once the undefined symbol issue is fixed).

**Comment by ovalhub** [comment]
On Fri, 15 Nov 2019, Seth Morton wrote:

> @ovalhub OK, I have everything set up except Windows (which I plan to 
> attempt). Here is the link to the build with this setup:
>
> https://travis-ci.com/SethMMorton/pyicu/builds/136782659
>
> - The currently active Python versions (2.7, 3.5, 3.6, 3.7, and 3.8) are 
> testing against ICU 65.1 and 55.2 (a random non-latest version I chose)

If there are too many builds for 'free' travis-ci plan, dropping Python 
3.5 and 3.6 could help.

> - All other ICU versions going back to 50.2 are tested against Python 3.8.

Great !

> - MacOS is tested against ICU 65.1 and Python 3.8 (could do more, but not 
> sure there is much value)

That is the version I develop against, so if I break the build I know 
immmediately. It'd be more useful to test it against an old ICU, like 55.2.
(or whatever version the current macosx is shipping with by default, if that
  is still the case).

> This is a LOT of builds. I have set up caching so hopefully ICU does not 
> need to be constantly re-built, just PyICU, but still - Travis-CI has this 
> to say about running a lot of jobs:
>> If you are on an open-source plan, please remember that Travis CI provides this service free of charge to the community. So please only specify the matrix you actually need.

Dropping some old Python 3.x versions could help.

> With that in mind, do you REALLY need to test against all previous ICU 
> versions? Here is my analysis of the failure modes from the linked build:

No, testing against the version installed on LTS Linux distros would be most 
useful. For example, this release cycle saw errors against ICU 55.1 (only, 
so far). Why are people running with such old versions ? probably because 
that's what their distro gives them ?

> - `NameError: name 'LocaleMatcher' is not defined`
>  - ICU versions 64.2, 63.2, 62.2, 61.2, 60.3, 58.3

LocaleMatcher appeared in ICU 65 and all its mentions should be inside
  #if ICU > 65 brackets. The fact that you were able to build with ICU 55 (?)
should prove that.
Having line numbers for the errors (or a link to the failed build) would be 
helpful.

> - Compilation errors arising from `Edits` class
>  - ICU version 59.2

The Edits class appeared in ICU 59, and similarly, all its mentions should 
be bracketed. Same argument as above.

> - Undefined symbol at runtime (something related to `FontInstance`)
>  - ICU versions 57.2, 56.2, 55.2, 54.2, 51.3

That's different. For ICU versions < 58 one must add 'icule' to the 
libraries to link against (see where this is done in setup.py, line 222).
'icule' contains the defunct LayoutEngine, dropped from ICU >= 58.

> - Missing members from `RelativeDateTimeFormatter`
>  - ICU version 53.2

That one appeared in ICU 53.
So it doesn't make sense that it can't be found when testing against ICU 
53.2

> - `gcc: error: unrecognized command line option '-Qunused-arguments'`
>  - ICU version 52.2

Are you using an older C++ compiler sometimes ?

> - `error: invalid new-expression of abstract class type 'PythonReplaceable'` (plus SO MANY compiler warnings)
>  - ICU version 50.2

Without the line number, I don't know what to say.

All these errors seems to show that there is something wrong with the setup 
you're working on. In particular, the build seems to be building with a 
version of ICU that is different from what the compiler thinks it's seeing.
This is all very strange.

> I think it would be wise to pick a representative selection of active 
> versions, perhaps 65.1, 64.2, 59.2, 57.2, 53.2, 52.2, and 50.2 (although 
> care should be taken to make sure all of 57.2, 56.2, 55.2, 54.2, and 51.3 
> pass once the undefined symbol issue is fixed).

Agreed: the ICU versions to test against should be the ones included in 
Linux LTS distros (first). In recent Linux distros (next). On Windows (a 
recent and an old ICU version). On MacOS, an old ICU version, ideally pre 
C++ 11, say ICU 55.

Thank you very much for all the work so far !

**Comment by SethMMorton** [comment]
As far as finding the line numbers of errors - all of that information can be found in the Travis-CI link I put in my last comment.

Also, I am not actively changing c++ versions - just using what the `setup.py` finds.

From my perspective the fact that the CI is running and finding errors is a success. My plan was to get the CI up-and-running (even if there are build errors unrelated to the CI) and then hand it over. Is this what you had in mind?

**Comment by SethMMorton** [comment]
> The fact that you were able to build with ICU 55 (?) should prove that.

ICU 55 build failed.

**Comment by ovalhub** [comment]
Weren't you able, outside of travis, to build with icu 55 ? (isn't this how this whole thread got started)

**Comment by ovalhub** [comment]
> On Nov 15, 2019, at 17:34, Seth Morton <notifications@github.com> wrote:
> 
> As far as finding the line numbers of errors - all of that information can be found in the Travis-CI link I put in my last comment.
> 
> Also, I am not actively changing c++ versions - just using what the setup.py finds.
> 
> From my perspective the fact that the CI is running and finding errors is a success. My plan was to get the CI up-and-running (even if there are build errors unrelated to the CI) and then hand it over. Is this what you had in mind?
> 
If there are build errors related to the CI, it's less than ideal but I can proceed - your work is valuable nonetheless...

**Comment by ovalhub** [comment]
The ICU 55.2 build failed because of this error:
  undefined symbol: _ZTIN6icu_5514LEFontInstanceE
This means that LayoutEngine wasn't linked in. The CI setup must include 'icule' in the libraries for ICU versions < 58 (as is done in setup.py, line 223)

**Comment by SethMMorton** [comment]
> If there are build errors related to the CI, it's less than ideal but I can proceed

Just to be clear, I meant errors *unrelated* to the CI (e.g. the CPP code needs fixing). I do not plan to hand you a broken CI configuration.

> Weren't you able, outside of travis, to build with icu 55

I used the ICU package Ubuntu within Travis-CI, which apparently is version 55. It's pre-built. I suppose since it is distro-installed it sets up all the environment variables correctly so that PyICU finds all that it needs. In the CI I have to set up the environment manually, so it's easy to miss stuff.

> This means that LayoutEngine wasn't linked in. The CI setup must include 'icule' in the libraries for ICU versions < 58 (as is done in setup.py, line 223)

I see.  If you could help me by spelling out other fixes I need to make like this one that would be helpful. I am not as familiar as what is needed to get everything working as you.

**Comment by ovalhub** [comment]
I installed ICU 55.2 and the build builds but the tests fail since the conditional code added to if __name__ == "__main__" doesn't seem to have an effect when running from setup.py test.
Working on a fix...

**Comment by ovalhub** [comment]
PyICU on trunk, buildt with ICU 55.2 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
PyICU on trunk (unchaged), built with ICU 58.3 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
PyICU on trunk, built with ICU 59.2 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
PyICU on trunk, built with ICU 50.2 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
PyICU on trunk (unchanged), built with ICU 61.2 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
PyICU on trunk (unchanged), built with ICU 57.2 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
PyICU on trunk (unchanged), built with ICU 63.2 sources now passes all tests with Python 3.8, 2.7.16 on MacOS.

**Comment by ovalhub** [comment]
I've now tested a bunch of older ICU versions locally, on Mac OS, and fixed the issues found.
I'm stopping now, waiting to see if CI finds more issues to be resolved.
(you still need to add icule to PYICU_LIBRARIES when ICU < 58, for the older builds to succeed)

**Comment by SethMMorton** [comment]
Wow! That fixed nearly all the issues!

There are still two left:

- ICU 53.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267070)
  - There are still missing member name compilation errors from the `RelativeDateTimeFormatter` class
- ICU 52.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267071)
  - I'm completely at a loss here. Whatever mechanism is deciding the CFLAGs to add to the `gcc` call is adding `-Qunused-arguments` for this ICU version and this ICU version only. The interesting thing is that `-Qunused-arguments` has *never* been a `gcc` option to my knowledge, but it *is* a `clang` option. I am observing (in general) that ICU is being built with `clang` but PyICU is being built with `gcc` (typically OK, they are binary compatible).  My guess is that for whatever reason the command-line arguments are getting mixed up for this ICU version only, but that's just a guess.

**Comment by ovalhub** [comment]
On Sat, 16 Nov 2019, Seth Morton wrote:

> Wow! That fixed nearly all the issues!
>
> There are still two left:
>
> - ICU 53.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267070)
>  - There are still missing member name compilation errors from the `RelativeDateTimeFormatter` class

I just committed a fix for that one now.

> - ICU 52.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267071)
>  - I'm completely at a loss here. Whatever mechanism is deciding the CFLAGs to add to the `gcc` call is adding `-Qunused-arguments` for this ICU version and this ICU version only. The interesting thing is that `-Qunused-arguments` has *never* been a `gcc` option to my knowledge, but it *is* a `clang` option. I am observing (in general) that ICU is being built with `clang` but PyICU is being built with `gcc` (typically OK, they are binary compatible).  My guess is that for whatever reason the command-line arguments are getting mixed up for this ICU version only, but that's just a guess.

I can't reproduce this here. Some of the compiler flags are set by python's 
setuptools itself and depend how python was compiled. If that version, 52.2, 
is the only one with this problem, it's certainly ok to drop it from the CI.
We have plenty of versions already...

**Comment by ovalhub** [comment]
On Sat, 16 Nov 2019, Seth Morton wrote:

> Wow! That fixed nearly all the issues!
>
> There are still two left:
>
> - ICU 53.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267070)
>  - There are still missing member name compilation errors from the `RelativeDateTimeFormatter` class

> - ICU 52.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267071)
>  - I'm completely at a loss here. Whatever mechanism is deciding the CFLAGs to add to the `gcc` call is adding `-Qunused-arguments` for this ICU version and this ICU version only. The interesting thing is that `-Qunused-arguments` has *never* been a `gcc` option to my knowledge, but it *is* a `clang` option. I am observing (in general) that ICU is being built with `clang` but PyICU is being built with `gcc` (typically OK, they are binary compatible).  My guess is that for whatever reason the command-line arguments are getting mixed up for this ICU version only, but that's just a guess.

That one seems to come from icu-config, see log:

(running 'icu-config --cxxflags --cppflags')
2304  Adding CFLAGS="-O3 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings 
-Wno-long-long --std=c++0x  -Qunused-arguments -Wno-parentheses-equality 
-D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_ATOMIC=1 
-I/home/travis/icu4c/include" from /home/travis/icu4c/bin/icu-config

Also, the --std=c++0x in there is suspicious. C++11 became a requirement 
much later than ICU 52.2. Are you sure that you're running the icu-config 
that corresponds to version of ICU you're testing against ?

**Comment by SethMMorton** [comment]
> Are you sure that you're running the icu-config
that corresponds to version of ICU you're testing against?

Not 100%. But I don't see how it could be otherwise - ICU isn't installed on the system and I'm only installing the one version per container.  I'll update the configuration to echo a bunch of configuration information so that we can be more sure. 

> I can't reproduce this here.

My guess is because you are on macos and `clang` is the default compiler there. I wonder if you could reproduce if you set `CC` to `gcc` before executing `setup.py`.

**Comment by ovalhub** [comment]
On Sat, 16 Nov 2019, Seth Morton wrote:

> Wow! That fixed nearly all the issues!
>
> There are still two left:
>
> - ICU 53.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267070)
>  - There are still missing member name compilation errors from the `RelativeDateTimeFormatter` class
> - ICU 52.2 (https://travis-ci.com/SethMMorton/pyicu/jobs/257267071)
>  - I'm completely at a loss here. Whatever mechanism is deciding the CFLAGs to add to the `gcc` call is adding `-Qunused-arguments` for this ICU version and this ICU version only. The interesting thing is that `-Qunused-arguments` has *never* been a `gcc` option to my knowledge, but it *is* a `clang` option. I am observing (in general) that ICU is being built with `clang` but PyICU is being built with `gcc` (typically OK, they are binary compatible).  My guess is that for whatever reason the command-line arguments are getting mixed up for this ICU version only, but that's just a guess.

Also, to be more explicit you're testing against the intended version of 
ICU, it'd be nice to have the version of ICU embedded into all the paths 
used:
   like you have -I/opt/python/3.8.0/include/python3.8
you should also have
   -I/home/travis/icu-52.2/include instead of -I/home/travis/icu4c/include

Same for $PATH, $LD_LIBRARY_PATH, etc...

On my mac, to test all these versions locally, without polluting my env, 
here is what I did to build and install ICU into its own tree:
   - tar -xvzf ~/tmp/downloads/icu4c-52_2-src.tgz
   - mv icu icu-52.2
   - cd icu-52.2
   - mkdir _install
   - cd source
   - ./runConfigureICU MacOSX --prefix ~/tmp/icu-52.2/_install
   - make
   - make install
then in PyICU's tree:
   - rm -rf build
   - DYLD_LIBRARY_PATH=~/tmp/icu-52.2/_install/lib PATH=~/tmp/icu-52.2/_install/bin:$PATH _install3/bin/python setup.py test
   - DYLD_LIBRARY_PATH=~/tmp/icu-52.2/_install/lib PATH=~/tmp/icu-52.2/_install/bin:$PATH _install2/bin/python setup.py test

**Comment by ovalhub** [comment]
On Sat, 16 Nov 2019, Seth Morton wrote:

>> Are you sure that you're running the icu-config
> that corresponds to version of ICU you're testing against?
>
> Not 100%. But I don't see how it could be otherwise - ICU isn't installed on the system and I'm only installing the one version per container.  I'll update the configuration to echo a bunch of configuration information so that we can be more sure.
>
>> I can't reproduce this here.
>
> My guess is because you are on macos and `clang` is the default compiler 
> there. I wonder if you could reproduce if you set `CC` to `gcc` before 
> executing `setup.py`.

On my mac, gcc and clang are identical, both say
   Apple LLVM version 8.1.0 (clang-802.0.42)
   Target: x86_64-apple-darwin18.6.0
   Thread model: posix
   InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by SethMMorton** [comment]
> On my mac, gcc and clang are identical

Right, I forgot about that.

**Comment by SethMMorton** [comment]
> It'd be nice to have the version of ICU embedded into all the paths used

I had originally done that, but found it to make the caching process more challenging and it wasn't necessary. I can bring it back if you'd like, but I think that the solution I just came up with should be fine. Keep in mind that Travis-CI uses a container (Docker) based mechanism, so each job is a "clean slate" so there is no mixing between them. It is really not possible for the data from one job to "leak" into another, so it's not possible to accidentally compile against the wrong ICU version unless one was already installed (which is not the case) or I downloaded the wrong one (unlikely).

**Comment by ovalhub** [comment]
On Sat, 16 Nov 2019, Seth Morton wrote:

>> It'd be nice to have the version of ICU embedded into all the paths used
>
> I had originally done that, but found it to make the caching process more 
> challenging and it wasn't necessary. I can bring it back if you'd like, 
> but I think that the solution I just came up with should be fine. Keep in 
> mind that Travis-CI uses a container (Docker) based mechanism, so each job 
> is a "clean slate" so there is no mixing between them. It is really not 
> possible for the data from one job to "leak" into another, so it's not 
> possible to accidentally compile against the wrong ICU version unless one 
> was already installed (which is not the case) or I downloaded the wrong 
> one (unlikely).

That makes sense, I didn't realize that.
What does the cache work, then, if it's all hermetic, in containers ?

**Comment by SethMMorton** [comment]
All of Travis's caching documentation are here: https://docs.travis-ci.com/user/caching/. I'm not quite sure what you are asking, but *think* this will answer your question: https://docs.travis-ci.com/user/caching/#how-does-caching-work.

**Comment by SethMMorton** [comment]
This may also be of interest: https://docs.travis-ci.com/user/caching/#caches-and-build-matrices

**Comment by SethMMorton** [comment]
It seems like the  `--cxxflags` output for ICU version 52.2 is broken. I am going to skip this version in the CI.

**Comment by SethMMorton** [comment]
All green!

With the new configuration information being output, I am now 100% confident the correct ICU is being used in all cases. I also note something interesting...

> Also, the --std=c++0x in there is suspicious. C++11 became a requirement much later than ICU 52.2.

For ICU version 50.2 and 51.3, they were including the `-std=c++11` flag, and then starting in 52.2 switched to `-std=c++0x`, then switched back at a later point.

**Comment by ovalhub** [comment]
Excellent !
Is your PR still WIP or can I merge it ?

**Comment by SethMMorton** [comment]
Still WIP.  I plan to add windows support. I'm excited to do that because I will apply what I learn here to my repos.

**Comment by ovalhub** [comment]
> On Nov 16, 2019, at 13:50, Seth Morton <notifications@github.com> wrote:
> 
> Still WIP. I plan to add windows support. I'm excited to do that because I will apply what I learn here to my repos.
> 
Cool, thank you !

**Comment by SethMMorton** [comment]
All right... I'm about ready to give up getting Windows to work.  After *many* failed attempts to even get it start compiling, it was able to compile for 13 minutes and then fail.

https://travis-ci.com/SethMMorton/pyicu/jobs/257412314

Looks like they invoke some python script near the end of the build, and it crashes because it assumes some item was in a list but it is not. 

Anyway... how much do you want Windows support in CI?

**Comment by ovalhub** [comment]
On Sat, 16 Nov 2019, Seth Morton wrote:

> All right... I'm about ready to give up getting Windows to work.  After 
> *many* failed attempts to even get it start compiling, it was able to 
> compile for 13 minutes and then fail.

From the logs, it looks like you're building a bunch of different windows 
configurations. Reading the ICU readme.html about installing on Windows, 
they seem to indeed have a bunch of variants:
   cygwin
   windows, then 32bit, 64bit, UWP (what is that ?), Release, Debug, ...
I think you should pick just *one*, say 64-bit, non UWP, Release, build so 
that the MSVC compiler is used (it has been the source of issues in the 
past).
Then, follow the ICU instructions to build using the command line using 
msbuild or devenv.com.
I saw that Travis considers "Windows builds an early access feature"...

> https://travis-ci.com/SethMMorton/pyicu/jobs/257412314
>
> Looks like they invoke some python script near the end of the build, and it crashes because it assumes some item was in a list but it is not.
>
> Anyway... how much do you want Windows support in CI?

It would be useful to have since I have no access to Windows at all.
But it's ok to give up if this proves too much of a pain (!)

**Comment by SethMMorton** [comment]
> From the logs, it looks like you're building a bunch of different windows configurations.

I don't think you are reading the logs correctly. I am only trying to get ICU built with MSVC. I attempted to do this with either cygwin (as in this build: https://travis-ci.com/SethMMorton/pyicu/jobs/257411610, which fails because it thinks the C compiler doesn't work) or the VS studio suite (as in this build: https://travis-ci.com/SethMMorton/pyicu/builds/136856342 which fails for who knows why) and neither worked. Each of these were in separate *builds*, e.g. different commits. At no point did I try to do both at the same time, that would be stupid.

> I think you should pick just *one*, say 64-bit, non UWP, Release, build so that the MSVC compiler is used (it has been the source of issues in the past). Then, follow the ICU instructions to build using the command line using msbuild or devenv.com.

That is *exactly* what I did in the job I linked to... have you taken a look at the code I am commiting? If not, here's a link to the line where I use the `msbuild` command (which I did read from the [ICU README](https://htmlpreview.github.io/?https://github.com/unicode-org/icu/blob/release-64-2/icu4c/readme.html#HowToBuildWindows)).

https://github.com/ovalhub/pyicu/blob/f394b35cecb3012f1effb5e29b81a775eaedb5db/ci-prepare-environment.bash#L114

And here's the line where *that* failed due to an error I have no idea how to debug: https://travis-ci.com/SethMMorton/pyicu/jobs/257412314#L3593.

**Comment by ovalhub** [comment]
> On Nov 17, 2019, at 10:50, Seth Morton <notifications@github.com> wrote:
> 
> From the logs, it looks like you're building a bunch of different windows configurations.
> 
> I don't think you are reading the logs correctly. I am only trying to get ICU built with MSVC. I attempted to do this with either cygwin (as in this build: https://travis-ci.com/SethMMorton/pyicu/jobs/257411610, which fails because it thinks the C compiler doesn't work) or the VS studio suite (as in this build: https://travis-ci.com/SethMMorton/pyicu/builds/136856342 which fails for who knows why) and neither worked. Each of these were in separate builds, e.g. different commits. At no point did I try to do both at the same time, that would be stupid.
> 
> I think you should pick just one, say 64-bit, non UWP, Release, build so that the MSVC compiler is used (it has been the source of issues in the past). Then, follow the ICU instructions to build using the command line using msbuild or devenv.com.
> 
> That is exactly what I did in the job I linked to...
> 
Last night, I followed the link you sent me and, finding the build logs, I saw the list of ICU files fly several times. I did not look at your code then.
I also saw that the DLLs seemed to have been built and saw the failure you reported with py.exe (which I'm just as mystified about as you).

**Comment by ovalhub** [comment]
> On Nov 17, 2019, at 10:50, Seth Morton <notifications@github.com> wrote:
> 
> From the logs, it looks like you're building a bunch of different windows configurations.
> 
> I don't think you are reading the logs correctly. I am only trying to get ICU built with MSVC. I attempted to do this with either cygwin (as in this build: https://travis-ci.com/SethMMorton/pyicu/jobs/257411610, which fails because it thinks the C compiler doesn't work) or the VS studio suite (as in this build: https://travis-ci.com/SethMMorton/pyicu/builds/136856342 which fails for who knows why) and neither worked. Each of these were in separate builds, e.g. different commits. At no point did I try to do both at the same time, that would be stupid.
> 
> I think you should pick just one, say 64-bit, non UWP, Release, build so that the MSVC compiler is used (it has been the source of issues in the past). Then, follow the ICU instructions to build using the command line using msbuild or devenv.com.
> 
> That is exactly what I did in the job I linked to... have you taken a look at the code I am commiting? If not, here's a link to the line where I use the msbuild command (which I did read from the ICU README).
> 
> https://github.com/ovalhub/pyicu/blob/f394b35cecb3012f1effb5e29b81a775eaedb5db/ci-prepare-environment.bash#L114
> 
I remember seeing something last night in the icu readme about adding something to the command line about skipping uwp (not near laptop right now to be more precise)

**Comment by SethMMorton** [comment]
OK. I will try that. If that doesn't work, then I will hand what I have over to you.

**Comment by ovalhub** [comment]
> On Nov 17, 2019, at 10:50, Seth Morton <notifications@github.com> wrote:
> 
> From the logs, it looks like you're building a bunch of different windows configurations.
> 
> I don't think you are reading the logs correctly. I am only trying to get ICU built with MSVC. I attempted to do this with either cygwin (as in this build: https://travis-ci.com/SethMMorton/pyicu/jobs/257411610, which fails because it thinks the C compiler doesn't work) or the VS studio suite (as in this build: https://travis-ci.com/SethMMorton/pyicu/builds/136856342 which fails for who knows why) and neither worked. Each of these were in separate builds, e.g. different commits. At no point did I try to do both at the same time, that would be stupid.
> 
> I think you should pick just one, say 64-bit, non UWP, Release, build so that the MSVC compiler is used (it has been the source of issues in the past). Then, follow the ICU instructions to build using the command line using msbuild or devenv.com.
> 
> That is exactly what I did in the job I linked to... have you taken a look at the code I am commiting? If not, here's a link to the line where I use the msbuild command (which I did read from the ICU README).
> 
> https://github.com/ovalhub/pyicu/blob/f394b35cecb3012f1effb5e29b81a775eaedb5db/ci-prepare-environment.bash#L114
> 
> And here's the line where that failed due to an error I have no idea how to debug: https://travis-ci.com/SethMMorton/pyicu/jobs/257412314#L3593.
> 
That link doesn't give me any line. Maybe that could explain our disconnect ?

**Comment by SethMMorton** [comment]
It's line 3593 (the last part of the URL).

**Comment by SethMMorton** [comment]
I am done.

Here is the state of things:

- All jobs are defined *explicitly* in the `jobs:` key, rather than using a build matrix. I did this because there was so much picking and choosing going on
  - All ICU versions are tested against Python 3.8
  - All Python versions are tested against ICU 65
  - MacOS tests ICU versions 65 and 55 on Python 3.8
  - Windows (currently disabled) tests ICU versions 65 and 55 on Python 3.8
- All the logic to build ICU (and to build Python on MacOS and Windows) is in the bash script `ci-prepare-environment.bash`. It is called in the `before_install:` section
  - It is in this file where building ICU in Windows needs to be modified if that is something you will do
- The ICU build and the (Python build on MacOS) is cached

I still have email notifications turned off, but I *highly* recommend turning them on (just delete the `notifications: email: false` from `.travis-ci.yml`. Travis only sends an email:

- On tagged releases
- When your build fails
- On the first successful build after a failure

Assuming you don't have too many failed builds, you won't get many emails.

**Comment by ovalhub** [comment]
> On Nov 17, 2019, at 11:05, Seth Morton <notifications@github.com> wrote:
> 
> It's line 3593 (the last part of the URL).
> 
Here is a screenshot of where your link sends me (and, no, I didn't notice the line number in it):

**Comment by ovalhub** [comment]
Thank you for your work and contribution !

**Pull request merged**
