### PR TITLE
Fix Windows setup problems

### PR DESCRIPTION
**Pull request by amynbe**
Integrated fixes from #7 and #42 and #44
Also added c:/icu/lib64 lib path to Win LFLAGS as that's what exists in the latest icu version 58.

### CODE REVIEW

**Comment by ovalhub** [comment]
I see you added lib64 to the win32 case.
What is the value of sys.platform on Windows 64-bit, is it win64 ?
(I have no access to Windows).

**Comment by amynbe** [comment]
sys.platform is always 'win32' on Windows.

**Comment by ovalhub** [comment]
On Wed, 22 Mar 2017, Amyn wrote:

> sys.platform is always 'win32' on Windows.

Even on Python 3 ?
For linux, on Python 3, sys.platform was changed from linux2 to linux.
No such change happened for Windows with Python 3 ?

**Comment by amynbe** [comment]
Even on python 3, which I'm using. 'win32' was kept for backward 
compatibility with older windows python scripts.22-Mar-17 11:15 PM 
ovalhub (notifications@github.com) 
On 
  Wed, 22 Mar 2017, Amyn wrote:> sys.platform is always 'win32' on 
  Windows.Even on Python 3 ?For linux, on Python 3, sys.platform was 
  changed from linux2 to linux.No such change happened for Windows with 
  Python 3 ?>> -- > You are receiving this because you 
  commented.> Reply to this email directly or view it on GitHub:> 
  https://github.com/ovalhub/pyicu/pull/47#issuecomment-288367514
  —You 
  are receiving this because you authored the thread.Reply to this email 
  directly, view it 
  on GitHub, or mute 
  the thread.
  
  
  
  
  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ovalhub/pyicu","title":"ovalhub/pyicu","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ovalhub/pyicu"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ovalhub in #47: \nOn Wed, 22 Mar 2017, Amyn wrote:\n\n\u003e sys.platform is always 'win32' on Windows.\n\nEven on Python 3 ?\nFor linux, on Python 3, sys.platform was changed from linux2 to linux.\nNo such change happened for Windows with Python 3 ?\n\n\u003e\n\u003e -- \n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly or view it on GitHub:\n\u003e https://github.com/ovalhub/pyicu/pull/47#issuecomment-288367514\n"}],"action":{"name":"View Pull Request","url":"https://github.com/ovalhub/pyicu/pull/47#issuecomment-288568868"}}}

**Comment by ovalhub** [comment]
I believe the issues reported here were fixed.

**Comment by ovalhub** [comment]
actually no, this has to do with adding lib64. Sorry for the noise.

**Pull request closed without merging**
